import { useState } from 'react';
import { Clock3, Mail, MapPin, PhoneCall } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { PageHero } from '@/components/ui/PageHero';
import { Section } from '@/components/layout/Section';
import { Container } from '@/components/layout/Container';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { siteConfig } from '@/data/siteConfig';
import { useAppDispatch } from '@/redux/hooks';
import { addToast } from '@/redux/slices/uiSlice';
export default function ContactPage() { const { t } = useTranslation(); const dispatch = useAppDispatch(); const [sent, setSent] = useState(false); return <><PageHero title="contact.title" description="contact.description" /><Section><Container className="grid gap-10 lg:grid-cols-[1fr_0.8fr]"><Card className="p-6 sm:p-9"><h2 className="text-2xl font-semibold text-[var(--color-ink)]">{t('contact.formTitle')}</h2><form className="mt-7 grid gap-5" onSubmit={(event) => { event.preventDefault(); setSent(true); dispatch(addToast({ message: t('common.success'), tone: 'success' })); }}><label className="grid gap-2 text-sm font-semibold"><span>{t('common.name')}</span><input className="input" required /></label><label className="grid gap-2 text-sm font-semibold"><span>{t('common.email')}</span><input className="input" type="email" required /></label><label className="grid gap-2 text-sm font-semibold"><span>{t('common.message')}</span><textarea className="input min-h-32 py-3" required /></label><Button type="submit">{sent ? t('common.success') : t('contact.send')}</Button></form></Card><div className="grid gap-5"><Card className="p-6"><h2 className="font-semibold text-[var(--color-ink)]">{t('contact.locationTitle')}</h2><div className="mt-5 flex h-48 items-center justify-center border border-[var(--color-border)] bg-[var(--color-surface)] text-center text-sm text-[var(--color-muted)]"><MapPin className="me-2 text-[var(--color-primary)]" size={18} />{siteConfig.contact.address}</div><p className="mt-4 flex gap-2 text-sm text-[var(--color-body)]"><MapPin className="shrink-0 text-[var(--color-primary)]" size={17} />{siteConfig.contact.address}</p></Card><Card className="p-6"><h2 className="font-semibold text-[var(--color-ink)]">{t('contact.hoursTitle')}</h2><div className="mt-4 grid gap-3 text-sm text-[var(--color-body)]"><p className="flex justify-between gap-4"><span className="flex items-center gap-2"><Clock3 size={16} className="text-[var(--color-primary)]" />{t('contact.days')}</span><b className="text-[var(--color-ink)]">{t('contact.hours')}</b></p><p className="flex gap-2"><PhoneCall size={16} className="text-[var(--color-primary)]" />{siteConfig.contact.phone}</p><p className="flex gap-2"><Mail size={16} className="text-[var(--color-primary)]" />{siteConfig.contact.email}</p></div></Card></div></Container></Section><Section tone="dark"><Container className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="eyebrow text-white/75">{t('contact.emergencyTitle')}</p><p className="mt-3 max-w-2xl text-white/90">{t('contact.emergencyDescription')}</p></div><a href={`tel:${siteConfig.contact.emergency}`} className="btn bg-white text-[var(--color-primary-dark)]"><PhoneCall size={17} />{siteConfig.contact.emergency}</a></Container></Section></>; }
