import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Search } from 'lucide-react';
import { PageHero } from '@/components/ui/PageHero';
import { Section } from '@/components/layout/Section';
import { Container } from '@/components/layout/Container';
import { ServiceCard } from '@/components/ui/ServiceCard';
import { services, type ServiceCategory } from '@/data/services';
import { cn } from '@/utils/cn';
export default function ServicesPage() { const { t } = useTranslation(); const [category, setCategory] = useState<'all' | ServiceCategory>('all'); const [query, setQuery] = useState(''); const filtered = useMemo(() => services.filter((service) => (category === 'all' || service.category === category) && t(service.titleKey).toLowerCase().includes(query.toLowerCase())), [category, query, t]); return <><PageHero title="services.title" description="services.description" /><Section><Container><div className="flex flex-col gap-5 border-b border-[var(--color-border)] pb-6 md:flex-row md:items-end md:justify-between"><label className="relative w-full md:max-w-sm"><span className="mb-2 block text-sm font-semibold text-[var(--color-ink)]">{t('common.search')}</span><Search className="absolute start-3 top-[2.65rem] -translate-y-1/2 text-[var(--color-muted)]" size={18} /><input className="input ps-10" placeholder={t('common.search')} value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="flex flex-wrap gap-2">{(['all', 'primaryCare', 'specialty', 'diagnostics'] as const).map((item) => <button key={item} className={cn('rounded-md border px-4 py-2 text-sm font-semibold transition', category === item ? 'border-[var(--color-primary)] bg-[var(--color-primary)] text-white' : 'border-[var(--color-border)] text-[var(--color-muted)] hover:border-[var(--color-primary)] hover:text-[var(--color-primary-dark)]')} onClick={() => setCategory(item)}>{t(item === 'all' ? 'services.all' : `services.${item}`)}</button>)}</div></div>{filtered.length ? <div className="mt-10 grid gap-x-12 md:grid-cols-2">{filtered.map((service) => <ServiceCard key={service.id} service={service} />)}</div> : <p className="py-20 text-center text-[var(--color-muted)]">{t('services.noResults')}</p>}</Container></Section></>; }
